[package]
name = "e_num_derive"
version = "0.1.0"
authors = ["coolreader18 <33094578+coolreader18@users.noreply.github.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.15"
darling = "0.8"
